spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&SSL=false
    username: root
    password: 123
    tomcat:
      max-active: 30
      max-wait: 1000
      max-idle: 20
      min-idle: 10
  thymeleaf:
    cache: false
    encoding: UTF-8
  mvc:
    static-path-pattern: /**
logging:
  level:
    com.bear.seckill: debug
  file: log/seckill.log
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080