spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&SSL=false
    username: root
    password: 123
    tomcat:
      max-active: 30
      max-wait: 1000
      max-idle: 20
      min-idle: 10
  thymeleaf:
    cache: false
    prefix: classpath:/templates/views/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
logging:
  level:
    com.bear.seckill: debug
  file: log/seckill.log
mybatis:
  mapper-locations: classpath:mapper/*.xml
